CREATE TABLE users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE short_urls (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    short_url VARCHAR(255) UNIQUE NOT NULL,
    origin_url VARCHAR(255) NOT NULL,
    date_of_creating DATE NOT NULL,
    date_of_expiring DATE,
    count_of_transition BIGINT DEFAULT 0,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);